export const skillCategories = [
  {
    id: 1,
    name: "Programming Languages",
    skills: ["C", "C++", "Python", "JavaScript"],
  },
  {
    id: 2,
    name: "Web Development",
    skills: [
      "HTML",
      "CSS",
      "Tailwind CSS",
      "Bootstrap",
      "React",
      "Django",
    ],
  },
  {
    id: 3,
    name: "Frontend Frameworks",
    skills: [
      "React",
      "Vite",
      "Component Architecture",
      "Hooks",
      "State Management",
    ],
  },
  {
    id: 4,
    name: "Backend & API Development",
    skills: [
      "Django",
      "Django REST Framework",
      "JWT Authentication",
      "REST API Design",
      "Database Modeling",
      "CRUD Operations",
    ],
  },
  {
    id: 5,
    name: "Databases",
    skills: ["PostgreSQL", "MySQL", "SQLite"],
  },
  {
    id: 6,
    name: "DevOps & Deployment",
    skills: [
      "Linux VPS",
      "Nginx",
      "Gunicorn",
      "CI/CD Basics",
      "Render Deployment",
      "Railway Deployment",
      "Vercel Deployment",
    ],
  },
  {
    id: 7,
    name: "Version Control & Tools",
    skills: ["Git", "GitHub", "Postman", "VS Code", "Figma (Basic)"],
  },
  {
    id: 8,
    name: "Phitron CSE Fundamental Course",
    skills: [
      "Data Structures",
      "Algorithms",
      "Linked List",
      "Stack",
      "Queue",
      "Hashing",
      "Sorting Algorithms",
      "Searching Algorithms",
      "Tree",
      "Binary Search Tree",
      "Graph Algorithms",
      "Recursion",
      "Backtracking",
      "STL",
      "Time Complexity",
      "Pointer & Memory Management",
      "Modular Programming",
      "Dynamic Programming (Basic)",
      "Problem Solving",
    ],
  },
  {
    id: 9,
    name: "Soft Skills",
    skills: [
      "Team Communication",
      "Leadership",
      "Problem Solving",
      "Requirement Analysis",
      "Project Planning",
    ],
  },
];
